name = "FileTrees"
uuid = "72696420-646e-6120-6e77-6f6420746567"
authors = ["Shashi Gowda <gowda@mit.edu>", "Julian Samaroo <jpsamaroo@jpsamaroo.me>"]
version = "0.3.1"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"

[compat]
AbstractTrees = "0.3"
Dagger = "0.9, 0.10, 0.11, 0.12.3"
FilePathsBase = "0.9"
Glob = "1.3"
julia = "1"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Dates", "DataFrames", "CSV", "Distributed"]
